### PR TITLE
Fix more deprecation warnings in LV2 wrapper

### PR DESCRIPTION
**Pull request by jatinchowdhury18**
Fixing the rest of the deprecation warnings I was getting from the LV2 wrapper and exporter. Probably should test with a couple more plugins before merging.

### CODE REVIEW

**Review by KottV — APPROVED** [review]

**Comment by KottV** [comment]
i really apologize, don't know why, but i haven't see that PR, Jatin

**Comment by KottV** [comment]
@jatinchowdhury18 
I have to revert it. Some presets became broken, and lv2_ttl_generator makes segfault on some plugins too.

**Comment by jatinchowdhury18** [comment]
@KottV, no worries! Could you share a couple of the plugins that had issues with broken presets and ttl generator segfaults, and I can follow up and try to fix it.

**Comment by KottV** [comment]
here is the presets from ChowKick
1 - "old", 2 - "new" with updated presets exporter
[chowkick_presets1.zip](https://github.com/lv2-porting-project/JUCE/files/6936467/chowkick_presets1.zip)
[chowkick_presets2.zip](https://github.com/lv2-porting-project/JUCE/files/6936470/chowkick_presets2.zip)

here is backtrace from https://github.com/reales/OB-Xd
```
Saving preset 81/129...
Program received signal SIGSEGV, Segmentation fault.
makePresetsFile (filter=0x7ffff6bb1010) at ../../Modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper_Exporter.cpp:448
448                 preset += "        lv2:symbol \"" + nameToSymbol(parameters[i]->getName (1024), j) + "\" ;\n";
(gdb) bt
#0  makePresetsFile (filter=0x7ffff6bb1010) at ../../Modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper_Exporter.cpp:448
#1  0x00007ffff77997c3 in createLv2Files (basename=0x7fffffffdd10 "OB-Xd") at ../../Modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper_Exporter.cpp:492
#2  0x00007ffff7799983 in lv2_generate_ttl (basename=0x7fffffffdd10 "OB-Xd") at ../../Modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper_Exporter.cpp:504
#3  0x000055555555537c in main ()
(gdb) list
443                   if (j == 0)
444                     preset += "    lv2:port [\n";
445                 else
446                     preset += "    [\n";
447
448                 preset += "        lv2:symbol \"" + nameToSymbol(parameters[i]->getName (1024), j) + "\" ;\n";
449                 preset += "        pset:value " + String::formatted("%f", safeParamValue(parameters[i]->getValue())) + " ;\n";
450
451                 if (j+1 == filter->getParameters().size())
452                     preset += "    ] ";
(gdb)
```
it hasn't lv2 support in main repo, so i'll provide the fork for you if you need it to test

**Comment by jatinchowdhury18** [comment]
Ah, looks like I had my `i` and `j` indexes flipped at those lines. It should be fixed now in the same branch, if you'd like to test it again?

**Comment by KottV** [comment]
I see)
>It should be fixed now in the same branch, if you'd like to test it again?

I'll be able to test it after tomorrow

**Pull request merged**
